### ISSUE TITLE
Sqlite3 Operational Error

### ISSUE THREAD

**Issue by GrayHatAli** [Jooyeshgar/amir#34]
Hello, I get this error.
`$ amir
/usr/lib/python3.7/site-packages/amir-0.3.0-py3.7.egg/amir/automaticaccounting.py:2: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: duplicate column name: permanent

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/amir", line 4, in <module>
    __import__('pkg_resources').run_script('amir==0.3.0', 'amir')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.7/site-packages/amir-0.3.0-py3.7.egg/EGG-INFO/scripts/amir", line 107, in <module>
    config = amirconfig.AmirConfig()
  File "/usr/lib/python3.7/site-packages/amir-0.3.0-py3.7.egg/amir/amirconfig.py", line 202, in __init__
    dbfile, self.db_repository, self.echodbresult)
  File "/usr/lib/python3.7/site-packages/amir-0.3.0-py3.7.egg/amir/database/__init__.py", line 63, in __init__
    api.upgrade(file, self.repository, self.version)
  File "/usr/lib/python3.7/site-packages/sqlalchemy_migrate-0.12.0-py3.7.egg/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "</usr/lib/python3.7/site-packages/decorator-4.4.0-py3.7.egg/decorator.py:decorator-gen-15>", line 2, in _migrate
  File "/usr/lib/python3.7/site-packages/sqlalchemy_migrate-0.12.0-py3.7.egg/migrate/versioning/util/__init__.py", line 167, in with_engine
    return f(*a, **kw)
  File "/usr/lib/python3.7/site-packages/sqlalchemy_migrate-0.12.0-py3.7.egg/migrate/versioning/api.py", line 366, in _migrate
    schema.runchange(ver, change, changeset.step)
  File "/usr/lib/python3.7/site-packages/sqlalchemy_migrate-0.12.0-py3.7.egg/migrate/versioning/schema.py", line 93, in runchange
    change.run(self.engine, step)
  File "/usr/lib/python3.7/site-packages/sqlalchemy_migrate-0.12.0-py3.7.egg/migrate/versioning/script/py.py", line 148, in run
    script_func(engine)
  File "/usr/lib/python3.7/site-packages/amir-0.3.0-py3.7.egg/amir/data/amir_migrate/versions/003_Version_3.py", line 85, in upgrade
    colPer.create(subject,  populate_default=True)
  File "/usr/lib/python3.7/site-packages/sqlalchemy_migrate-0.12.0-py3.7.egg/migrate/changeset/schema.py", line 577, in create
    engine._run_visitor(visitorcallable, self, connection, **kwargs)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2033, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/lib/python3.7/site-packages/sqlalchemy_migrate-0.12.0-py3.7.egg/migrate/changeset/ansisql.py", line 56, in traverse_single
    ret = super(AlterTableVisitor, self).traverse_single(elem)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3.7/site-packages/sqlalchemy_migrate-0.12.0-py3.7.egg/migrate/changeset/databases/sqlite.py", line 148, in visit_column
    super(SQLiteColumnGenerator,self).visit_column(column)
  File "/usr/lib/python3.7/site-packages/sqlalchemy_migrate-0.12.0-py3.7.egg/migrate/changeset/ansisql.py", line 104, in visit_column
    self.execute()
  File "/usr/lib/python3.7/site-packages/sqlalchemy_migrate-0.12.0-py3.7.egg/migrate/changeset/ansisql.py", line 44, in execute
    return self.connection.execute(self.buffer.getvalue())
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1155, in _execute_text
    parameters,
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python3.7/site-packages/SQLAlchemy-1.3.3-py3.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: permanent
[SQL: 
ALTER TABLE subject ADD permanent BOOLEAN]
(Background on this error at: http://sqlalche.me/e/e3q8)
`
*Additional information:
`$ uname -a
Linux GrayHat 5.1.3-arch1-1-ARCH #1 SMP PREEMPT Thu May 16 20:59:36 UTC 2019 x86_64 GNU/Linux`

**Comment by hadi60** [comment]
Hi,
Please confirm that your config directory is empty and you haven't any previous database.
1. backup your amir config directory "~/.amir/" be careful your database is here.
2. rm -fr ~/.amir/
3. test again
